export const ITEMS_PER_PAGE = 21;
export const COLLECTIONS_PER_PAGE = 21;
export const DASHBOARD_COLLECTIONS_LIMIT = 6;
export const DASHBOARD_RECENT_ITEMS_LIMIT = 10;
export const SEARCH_ITEMS_LIMIT = 500;
export const SEARCH_COLLECTIONS_LIMIT = 500;
